### ISSUE TITLE
Consider targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by khellang** [mcintyre321/OneOf#101]
Hi @mcintyre321! 👋🏻 

Would you consider adding a `netstandard2.0` target (and possibly dropping `netstandard1.6`) to get rid of the big `NETStandard.Library` dependency?

We're getting Snyk errors related to OneOf because it has the `NETStandard.Library` dependency:

![image](https://user-images.githubusercontent.com/582487/145996977-417524f9-140a-4092-9046-c25c390e57e2.png)

**Comment by mcintyre321** [comment]
Sounds good to me  - are you able to send a PR?

**Comment by khellang** [comment]
Done! #102

Removing `netstandard1.3` is probably an issue for another day, as it's a more invasive (breaking) change.
