### ISSUE TITLE
Source Generation fails when referenced by multiple projects

### ISSUE THREAD

**Issue by TomasMorton** [mcintyre321/OneOf#103]
I'm using the source generation, and it works great when a single project references the package, but as soon as I try to add `[GenerateOneOf]` in a second project I get conflicts.

>
```
'Class.cs(12, 6): [CS0436] The type 'GenerateOneOfAttribute' in 'OneOf.SourceGenerator/OneOf.SourceGenerator.OneOfGenerator/GenerateOneOfAttribute.cs' conflicts with the imported type 'GenerateOneOfAttribute' in 'OtherProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'OneOf.SourceGenerator/OneOf.SourceGenerator.OneOfGenerator/GenerateOneOfAttribute.cs'.
```

The import I'm using in both projects has `PrivateAssets="all"`, since without that I had XML comment issues (#104), but it seems to fail either way.
```
    <PackageReference Include="OneOf.SourceGenerator" Version="3.0.205" PrivateAssets="all" />
```

It's worth it to note that I'm using `DisableTransitiveProjectReferences` and `WarningsAsErrors`.

Workaround: Add `#pragma warning disable 0436` in each of my classes using the generator.

**Comment by romfir** [comment]
Analyzer/Source Generator is being run in every referenced project, changing Attribute to Internal will fix this.  This error is normally just a warning, but I will fix this in the same pr as the #104
