### ISSUE TITLE
No XML comments on generated methods leads to build failures

### ISSUE THREAD

**Issue by TomasMorton** [mcintyre321/OneOf#104]
I'm using the Source Generator, but when I add the `[GenerateOneOf]` attribute to a project that requires XML comments, it fails with:

```
Error CS1591 : Missing XML comment for publicly visible type or member 'Type.explicit operator InternalServiceError(Type)'
Error CS1591 : Missing XML comment for publicly visible type or member 'GenerateOneOfAttribute'
```

I've tried:
* Adding `generated_code = true` to editor config,
* Adding #pragma disable in the declaration of the OneOf,
* Using `assembly: SuppressMessage`

Is it possible to:
* Add the missing XML comments, or
* Add a pragma disable, or
* Make the methods internal (likely not, but it's an option!), or
* Something else from the analyzer world to help out?

**Comment by romfir** [comment]
I will add ```#pragma warning disable 1591``` in a PR, FYI the same issue exists with System.Text.Json source generator, I've reported an issue there: https://github.com/dotnet/runtime/issues/64499

**Comment by TomasMorton** [comment]
Thank you!
