### ISSUE TITLE
Source Generation produce invalid code with interfaces

### ISSUE THREAD

**Issue by Kuinox** [mcintyre321/OneOf#115]
Hello.
When using OneOf code generation on such class:
```csharp
[GenerateOneOf]
public partial class SingleOrMultiStatementSymbol : OneOfBase<ISymbolWithAStatement, StatementBlockSymbol> { }
````
It generate:
```csharp
public partial class SingleOrMultiStatementSymbol
{
    public SingleOrMultiStatementSymbol( OneOf.OneOf<ISymbolWithAStatement,StatementBlockSymbol> _ ) : base( _ ) { }

    public static implicit operator SingleOrMultiStatementSymbol(ISymbolWithAStatement _ ) => new SingleOrMultiStatementSymbol( _ );
    public static explicit operator ISymbolWithAStatement( SingleOrMultiStatementSymbol _ ) => _.AsT0;

    public static implicit operator SingleOrMultiStatementSymbol( StatementBlockSymbol _ ) => new SingleOrMultiStatementSymbol( _ );
    public static explicit operator StatementBlockSymbol( SingleOrMultiStatementSymbol _ ) => _.AsT1;
}
```
Which would lead to an error `user-defined conversions to or from an interface are not allowed`.
For some reason, VS do not show any error on generated code, and instead simply refuse to cast which is confusing.

**Comment by romfir** [comment]
@mcintyre321 what do you think should happen in this case? We can either return an error to the user when `GenerateOneOf` is used on `OneOfBase` with interfaces or simply do not generate conversion for an interface and generate the others normally

**Comment by mcintyre321** [comment]
A visible error is better, IMO.

**Comment by Kuinox** [comment]
A good alternative, that could be always generated, is a `From` method for each type.
