### ISSUE TITLE
How to widen eg. `OneOf'3` to `OneOf'4` nicely

### ISSUE THREAD

**Issue by ljani** [mcintyre321/OneOf#127]
I'd like to widen an instance of eg. `OneOf<Empty, InProgress, Failed>` to `OneOf<Empty, InProgress, Failed, Success>` to call a method accepting `OneOf<Empty, InProgress, Failed, Success>`. Are there any suggestions how to handle this nicely?

Adding an extension method is one solution, but calling it is a feels a little cumbersome with all the generics:

```csharp
public static OneOf<T0, T1, T2, T3> Widen<T0, T1, T2, T3>(this OneOf<T0, T1, T2> oneOf)
{
    return oneOf.Match(OneOf<T0, T1, T2, T3>.FromT0, OneOf<T0, T1, T2, T3>.FromT1, OneOf<T0, T1, T2, T3>.FromT2);
}
```

```csharp
var all = instance.Widen<Empty, InProgress, Failed, Success>();
```

It'd much nicer to call eg.

```csharp
var all = instance.WidenWith<Success>();
```

I also thought of using a type holder, which I can implement as an extension method and the compiler will infer the generics:

```csharp
var all = instance.WidenWith(TypeHolder.For<Success>());
```

Also, have you considered some intersect method for types with a common interface? Currently, I'm using an extension method, which is kind of okay:

```csharp
public static TResult Intersect<TResult, TIntersection, T0, T1, T2>(
    this OneOf<T0, T1, T2> oneOf,
    Func<TIntersection, TResult> selector
)
    where T0 : TIntersection
    where T1 : TIntersection
    where T2 : TIntersection
{
    var intersection = oneOf.Match<TIntersection>(t0 => t0, t1 => t1, t2 => t2);
    return selector(intersection);
}
```

And to call it:

```csharp
var name = instance.Intersect((IHasName) x => x.Name);
```

A generic method would be a little nicer though I think, if I didn't have to specify all the generic parameters:

```csharp
var name = instance.Intersect<IHasName>(x => x.Name);
```

**Comment by mcintyre321** [comment]
I think you can express this pretty cleanly like so
```
OneOf<A, B> x = new A();
var y = x.Match<OneOf<A, B, C>>(_ => _, _ => _);
```
