### ISSUE TITLE
Source generator should work on internal classes, too

### ISSUE THREAD

**Issue by cytoph** [mcintyre321/OneOf#130]
The source generator could easily find out the visibility of the class and use the same visibility for the generated partial class code. So why is it necessary for the class public?

**Comment by dnperfors** [comment]
The source generator specifically creates a public partial class, if the `public` is removed, the type would get the visibility of the one that actually specifies the visibility... 
I wouldn't mind creating a PR for this.

**Comment by cytoph** [comment]
I didn't know that was possible (omitting the visibility so it uses the visibility of another part of the class where it is set). If so, that of course would be an option, too.
