### ISSUE TITLE
OneOf vs ValueOf ?

### ISSUE THREAD

**Issue by marcusx2** [mcintyre321/OneOf#137]
Pardon my ignorance, but I read about the [ValueOf](https://github.com/mcintyre321/valueof) library, and it looks similar to this one. What can this library do that ValueOf can't, and vice versa? Thanks!

**Comment by romfir** [comment]
`ValueOf` provides a simple way to create [Value Objects](https://en.wikipedia.org/wiki/Value_object) which by definition can contain multiple values (or just one!) and possibly some validation for them. They are one of the ways to get rid of the [primitive obsession](https://enterprisecraftsmanship.com/posts/collections-primitive-obsession/)

While `OneOf` provides a way to create [discriminated unions](https://en.wikipedia.org/wiki/Tagged_union) - a type that  contains exactly one value for one of its defined types. 

Please check both projects readme and tests to know more :)

**Comment by marcusx2** [comment]
@mcintyre321 

If I wanted to define a type that could be one of a few possible strings, would I use ValueOf or OneOf? It can't contain multiple values, just one value, but it's also just one type.

Something like this in typescript

`export type mycustomstringtype =| 'x'| 'y'| 'z'| 'w';`

**Comment by emperador-ming** [comment]
I would probably use SmartEnum in that case.
https://github.com/ardalis/SmartEnum

**Comment by mcintyre321** [comment]
If you're switching behaviour on the values then OneOf, otherwise a valueof
or enum or maybe that smartenum
