### ISSUE TITLE
Extra Utility Methods

### ISSUE THREAD

**Issue by rtkelly13** [mcintyre321/OneOf#15]
I think there are a couple of useful methods that could be useful in this library, specifically for the OneOf Struct. 

The two I am thinking of would be
1. Return
2. Map

Even though there are implicit converters, that approach fails when using interfaces. There are two ways I have typically gotten around that by implementing OneOf<T1, T2..> Return (T1 input) => input but might be a good addition. The other is to implement a class which holds the Interface inside of it to side step the issue, making the first workaround part of OneOf itself might be a nice change as I have found myself wanting to have a way to construct OneOf without having to rely on a typed variable.

Map would Take a OneOf<T1,T2 ...> and Func<T1, TResult> with different overloads for each Generic type we would want to replace and the result would be OneOf<TResult, T2..> 

I'm a big fan of this library and it has started showing up all over the codebase I work on, I would like to know if you are interested in this kind of change.

**Comment by mcintyre321** [comment]
So the `Return` is a static factory that you can pass the interface into? e.g.

`
OneOf<Bar, IFoo> GetData(int x, Bar bar, IFoo foo){
   if (x == 0) return bar;
   return OneOf<Bar, IFoo>.Result(foo);

}
`
Is that what you mean?

**Comment by rtkelly13** [comment]
I had originally thought foo.Return<Bar, IFoo>() but that approach is more fitting.

I have been working on an implementation of this but I will modify to use that api and will get a PR to you.

This also includes a map implementation which is currently an extension method.
`
        public static OneOf<T0, TResult> Map<T0, T1,TResult>(this OneOf<T0, T1> input, Func<T1, TResult> mapFunc)
        {
            if(mapFunc == null)
            {
                throw new ArgumentNullException(nameof(mapFunc));
            }
            return input.Match<OneOf<T0, TResult>>(
                input0 => input0,
                input1 => mapFunc(input1)
            );
        }
`

**Comment by rtkelly13** [comment]
Created the PR https://github.com/mcintyre321/OneOf/pull/16
Had to deal with the ambiguous usages of map, couldn't think of a better name than the MapTX
Also noticed that OneOf.csproj has a reference to Newtonsoft.Json which is only used by the test lib, so moved it over to just there. 
That should remove the Dependency from the package also which I think is a positive.

**Comment by mcintyre321** [comment]
Do you think you could change `.Result` to `OneOf<IFoo, Bar>.FromT1(bar);`? This would eliminate any errors which might arise where `Bar` might implement `IFoo`

**Comment by rtkelly13** [comment]
Updated to include that change, should have seen that from the issues I had with Map really.

**Comment by mcintyre321** [comment]
The `From` methods don't work for `OneOfBase`, but I've had a thought on how they could...

For `class TrueOrFalse : OneOfBase<True, False> {  } ` the `.From` will return `OneOfBase<True, False
