### ISSUE TITLE
Generated source is incompatible with JsonSerializerContext generated code

### ISSUE THREAD

**Issue by alex34533-hpinc** [mcintyre321/OneOf#159]
Hello,

I'm using **JsonSerializerContext** with source generator, here an simple class example:

```
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified, GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(StringOrBool))]
public partial class ExampleJsonContext : JsonSerializerContext
{
}
```

**StringOrBool** is a class generated by **[GenerateOneOf]** : 

```
[GenerateOneOf]
public partial class StringOrBool : OneOfBase<string, bool> { }

```

Which produce the following constructor:

`public StringOrBool(OneOf.OneOf<string, bool> _) : base(_) { }`

However, **JsonSerializerContext** seams to not be able to handle the discard operator and fail to compile, trying to call a parameter-less constructor.

Using the following constructor fix the issue:

`public StringOrBool(OneOf.OneOf<string, bool> input) : base(input) { }`

**Comment by romfir** [comment]
Hi, this happens due to the fact that source generators cannot read other source generated code, in this specific case `System.Text.Json` does not see constructor generated in OneOf SourceGenerator. there is an [issue](https://github.com/dotnet/roslyn/issues/57239) with simillar problems (eg with Blazor Source generator and Regex one). If one would write code generated by the OneOf SourceGen by hand, something like this:
```csharp
public class StringOrBool : OneOfBase<string, bool>
{
    public StringOrBool(OneOf.OneOf<string, bool> _) : base(_) { }

    public static implicit operator StringOrBool(string _) => new StringOrBool(_);
    public static explicit operator string(StringOrBool _) => _.AsT0;

    public static implicit operator StringOrBool(bool _) => new StringOrBool(_);
    public static explicit operator bool(StringOrBool _) => _.AsT1;
}
```
and create context such as
```csharp
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified, GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(StringOrBool))]
public partial class ExampleJsonContext : JsonSerializerContext
{
}
```

the code would compile but would cause an runtime error during deserialization :) 

I think for (de)serialization one should use `IOneOf` interface eg
```csharp
JsonSerializer.Serialize<IOneOf>(new StringOrBool("a"));
```

with `System.Text.Json` source gen:
```csharp
var jsonString = JsonSerializer.Serialize(new StringOrBool(true), ExampleJsonContext.Default.IOneOf);
```
context:
```csharp
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified, GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(IOneOf))]
[JsonSerializable(typeof(StringOrBool))]
//[JsonSerializable(typeof(string))]
//[JsonSerializable(typeof(bool))]
//context must know all types that are in StringOrBool so we must add [JsonSerializable(typeof(StringOrBool))] or all types manually
public partial class ExampleJsonContext : JsonSerializerContext
{
}
```

so the only json context that would work with both source generatos is this:
```csharp
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified, GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(IOneOf))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(bool))]
public partial class ExampleJsonContext : JsonSerializerContext
{
}
```

**Comment by alex34533-hpinc** [comment]
> Hi, this happens due to the fact that source generators cannot read other source generated code

Oh yes, I knew that, but completely forgot about it when I encounter the issue and didn't though it could be that!

At first, it was compiling by writing my OneOf types by hand and it didn't occur to me that it was the double source generator issue (since a error was not pointing in that direction).
I indeed encounter issue with (de)serialization and ended up using my own JsonConverter.

I've now moved back to Generated OneOf ;)

```cs
[JsonConverter(typeof(DoubleOrDateTimeJsonConverter))]
[GenerateOneOf]
public partial class DoubleOrDateTime : OneOfBase<double, DateTime> { }
```

```cs
public class DoubleOrDateTimeJsonConverter : JsonConverter<DoubleOrDateTime>
{
    public override DoubleOrDateTime Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Number && reader.TryGetDouble(out var d))
        {
            return new DoubleOrDateTime(d);
        }
        if (reader.TokenType == JsonTokenType.String && reader.TryGetDateTime(out var dt))
        {
            return new DoubleOrDateTime(dt);
        }

        throw new InvalidOperationException("DoubleOrDateTime only support Double and DateTime.");
    }

    public override void Write(
        Utf8JsonWriter writer,
        DoubleOrDateTime doubleOrDateTime,
        JsonSerializerOptions options)
    {
        doubleOrDateTime.Switch(
            writer.WriteNumberValue,
            writer.WriteStringValue);
    }
}
```

Thank you for the clear explanation and sorry for the time lost.
