### ISSUE TITLE
OneOfBase with more than 7 generic types?

### ISSUE THREAD

**Issue by wtaisto** [mcintyre321/OneOf#163]
I have a use case with 13 possible generic types (with a decent chance of adding a handful more,) but it appears OneOfBase is only defined for up to 7 generic types.  I get that those OneOfBase<...> variations were probably auto-generated, and there would always thus be some upper bound on how many there are.  Is there some functional coding notion that suggests if you have more than 7, you should be using a different paradigm?

Possible fix: the convention for generating OneOfBase's via the OneOf.SourceGenerator is currently:

```
[GenerateOneOf]
public partial class MySpecialOneOf : OneOfBase<FirstType, SecondType, ThirdType> {}
```

What if there was an alternate mode, where the convention was like this:

```
[GenerateOneOfAlternate]
public partial class MySpecialOneOf<FirstType, SecondType, ThirdType> {}
```

The source generator would be responsible for setting the base class in the generated code (as it knows it should derive from OneOfBase), and also generate the OneOfBase with the required number of generic types (if greater than 7).  Or perhaps in that mode it wouldn't bother with generating the OneOfBase, and just stick that functionality directly into the generated class body.

**Comment by mcintyre321** [comment]
It was cut off to reduce assembly size. You can install OneOf.Extended, or
make T7 another OneOf

**Comment by wtaisto** [comment]
Aha!  Of course.  Thanks!
