### ISSUE TITLE
OneOf.Switch return value for Happy Path

### ISSUE THREAD

**Issue by wtaisto** [mcintyre321/OneOf#164]
I'm using OneOf as the return type from some methods, most of which have a primary return value, and then one or more warning or error types.  This is great, but because the Switch method takes delegates, the body of the delegate cannot participate in outer control flow, such as breaking / continuing a loop or returning.  I find myself at times having to add captured boolean flags or setting a captured variable to null so that after the Switch(), I know which type got Switched.

What if the Switch method returned the index of the case which was caught?  Even easier would be if it just returned true if the first type was matched, and false otherwise (assuming the OneOf's have been set up so that the first type is the Happy Path.)  But the index based return would probably have more broad utility.

Or is there again something I've missed, which is intended to solve this?

**Comment by bartelink** [comment]
in general the idea is that you're driven toward handling the bodies per result type
AFAICR there are `IsX` operators on the result type to check whether it's a specific result?
(have not looked at API in years; working from memory, but didnt want to leave you hanging)

**Comment by wtaisto** [comment]
Thanks so much!  Yes, if I grab the OneOf result value from one of my methods into a variable, then I can switch on it and later check the IsX bools.  But I guess I was hoping for a solution that allowed a more fluent programming style.  Really it was just sorta syntactic sugar.

**Comment by mcintyre321** [comment]
Using IsA and AsA isn't recommend as you lose exhaustive matching. The
TryPickT1 methods can be used for conditional logic
