### ISSUE TITLE
Default says that it's T0

### ISSUE THREAD

**Issue by ndrwrbgs** [mcintyre321/OneOf#29]
**Problem**: default(OneOf<T...>) will say that it is T0, and return default(T0) for `.Value`
**Suggestion**: Modify `_index` to be 1-based-index instead of 0-based, so that default(OneOf) can be distinguished from OneOf.FromT0(default)

```C#
var value = default(OneOf<int, string>);
Assert.IsFalse(value.IsT0); // True today
Assert.IsFalse(value.IsT1);
Assert.AreNotEqual(default(int), value.Value); // True today
```

**Comment by mcintyre321** [comment]
Good idea - I'll do that when I get a chance, PR happily accepted in the meantime!

**Comment by ndrwrbgs** [comment]
https://github.com/mcintyre321/OneOf/blob/c08d1d3d6312d2e3cd8144feec28de0e9a051dea/OneOf.Tests/DefaultConstructorTests.cs#L8-L13

It seems this would be a breaking change. I'm preparing it anyway but of note that if it's taken it'll need a major version bump.
