### ISSUE TITLE
Question/request: Is it possible to get a signed version of OneOf?

### ISSUE THREAD

**Issue by luminescent** [mcintyre321/OneOf#38]
Hi 

Would you consider/ be able to release a signed version of this library? I am getting some errors referencing it as it does not have a strong name. 

(Similar situation to this: https://stackoverflow.com/questions/1669139/signing-an-unsigned-assembly) 

Thank you.

**Comment by mcintyre321** [comment]
So I think you should be able to use https://github.com/dsplaisted/strongnamer - please let me know if this does (or doesn't) help.

**Comment by luminescent** [comment]
While that package looks really useful (thank you!), I am in a situation where it does not work for a few reasons: 

- I am referencing OneOf from a dependency of the main project (another project packaged up as nuget), and also from the main project. That means I need to add a reference to StrongNamer in both projects, and, then, the public key of the OneOf assembly won't match between these two and I will get compilation errors (e.g. I have changed only the main project and already getting them). 

- My projects target net462, but they use the .net core format. StrongNames post build task won't work with `dotnet build` , but only with `MSBuild`. Both my CI and local environments rely on the dotnet CLI for building.  

Hope this makes sense!

**Comment by mcintyre321** [comment]
Are both these projects under your control? It may be easiest to create an internal signed build of OneOf.


I had hoped StrongNamer was the answer to all this, but it looks like the x-plat story for it has hit a roadblock: https://github.com/dsplaisted/strongnamer/issues/17

I'm loathe to add StrongNaming - I myself haven't worked in an environment where it's required, and don't fully understand the ramifications of adding it, but I do know it can cause a lot of headaches and support questions, and I can find a lot of articles telling me not to do it. And few telling me to do it also.

Do you have some good literature on the pros/cons in 2019?

**Comment by mcintyre321** [comment]
> That means I need to add a reference to StrongNamer in both projects, and, then, the public key of the OneOf assembly won't match between these two and I will get compilation errors (e.g. I have changed only the main project and already getting them).

I think you'd only need this in the main project, because it is the one needing Strong Names?

**Comment by luminescent** [comment]
I have tried adding it in the main project only, but it won't compile.

**Comment by luminescent** [comment]
Some good literature - no. I need this because my main project needs to target 462 because of another dependency (outside of my control). And due to company policy, the dependency that needs OneOf needs to have a strong name. I sadly cannot change that. Since that is having a strong name, my main project needs to reference all signed assemblies. 

So I'd say the reasons in my case are company policies (motivated by security concerns). However we do none of this in the .net core projects that target netcoreapp.

**Comment by mcintyre321** [comment]
This dependency that uses OneOf - you must have some control over it, as you'd need to a. upgrade it to use Strong Named-OneOf, and b. strong name it too, right? If that's the case, can you make it depend on an internal SN copy of OneOf?

**Comment by luminescent** [comment]
Yes, exactly, the solution which will definitely work is make an internal copy of OneOf, called something like OneOf.Signed, with a strong name, and reference that from both the main and the dependent project.

However I was trying to avoid maintaining a copy of OneOf, as I will have to update it every time I need to upgrade, remember to reference this particular one etc. I completely understand that it would be extra work for you as well, releasing a signed version!

**Comment by mcintyre321** [comment]
It'd be great if you are able to keep it on an internal nuget feed if possible, having it out there publicly could cause some problems with compatibility down the line. Obviously it's MIT though you can do whatever you want!

**Comment by luminescent** [comment]
Ok, thank you for the explanations.

**Comment by caioproiete** [comment]
@mcintyre321 I recommend watching the talk [Build Great Libraries using .NET Standard](https://channel9.msdn.com/Events/dotnetConf/2018/S107) from the .NET Conf 2018 for some interesting reasons why strong naming is a good idea.

[![image](https://user-images.githubusercontent.com/177608/59347540-4f785480-8ceb-11e9-8ef0-0a14ce128eb3.png)](https://channel9.msdn.com/Events/dotnetConf/2018/S107)

---

There's also some good documentation in the .NET Core repo: [corefx/Strong Name Signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md)

**Comment by AsakusaRinne** [comment]
Hi, I'm using Oneof in our project and thanks a lot for all your works. For some reason, my project is required to sign the assembly. When using our package with .NET core, there's no problem. However when using .NET Framework (for example, 4.8), the compilation will fail and say Oneof.dll is not signed.

Since the only dependency of Oneof is Microsoft.SourceLink.GitHub, I think signing Oneof assembly will not bring negative effects Could you please re-consider it?
