### ISSUE TITLE
Add ToString formatter to OneOf

### ISSUE THREAD

**Issue by nzbart** [mcintyre321/OneOf#40]
Right now, formatting an instance of `OneOf` results in a string like this:
``OneOf.OneOf`2[Some.Custom.Type]``. Do you have any objections to me submitting a PR with a custom formatter that outputs a more useful representation of the underlying value?

If you're OK with that, what format would you like the string to take?

**Comment by mcintyre321** [comment]
Interesting... maybe for `OneOf<string, int> foo = 123;
Assert.Equal("System.Int32: 123");`

i.e {FullTypeNameOfInnerValue} {innerValue.ToString()}

What do you think?

**Comment by nzbart** [comment]
@mcintyre321 sounds reasonable to me. Would you like me to submit a PR, or will you make the change?

**Comment by mcintyre321** [comment]
PR please! If you could throw in a few tests, that would be great.

You'll need to edit the Linqpad file that generates the script, and run it to create the updated OneOf files.

**Comment by nzbart** [comment]
PR submitted for your review.
