### ISSUE TITLE
Question: How to use with async / await?

### ISSUE THREAD

**Issue by mattfrear** [mcintyre321/OneOf#41]
Question: is there a way to call Match with async / await? Related to #26 

I have:
```csharp
public async Task<OneOf<Foo, None>> HandleAsync(GetFooQuery query)
{
	var foo = await GetByIdAsync(query.FooId);

	return foo.Match<OneOf<Foo, None>>(
		f => GetCustomerNameForFooAsync(f).Result,
		_ => new None());
}

private async Task<OneOf<Foo, None>> GetByIdAsync(FooId fooId)
{ ...

private async Task<Foo> GetCustomerNameForFooAsync(Foo foo)
{ ...
```
but the `.Result` on the end is a bit icky (edit: and is not asyncronous!). Would be nice if I could do something like:
```csharp
public async Task<OneOf<Foo, None>> HandleAsync(GetFooQuery query)
{
	var foo = await GetByIdAsync(query.FooId);

	return foo.Match<OneOf<Foo, None>>(
		async f => await GetCustomerNameForFooAsync(f),
		_ => new None());
}
```

**Comment by luhis** [comment]
In your case I would do this
```CSharp
public Task<OneOf<object, None>> HandleAsync(int query)
        {
            var foo = await GetByIdAsync(query.FooId);

            return foo.Match<Task<OneOf<object, None>>>(
                f => GetCustomerNameForFooAsync(f),
                _ => Task.FromResult<OneOf<object, None>>(new None()));
        }
```

You just need to make sure that both routes return Task<OneOf<Foo, None>> and you should be okay.  I have found that these implicit conversions are a bit of  pain in cases like this.  That should get you compiling, but you might find a neater way to do the conversions from the instances, into the unions, into the tasks.  In my stuff I tend to added extension methods to clean it up

**Comment by mattfrear** [comment]
Thank you for the suggestion @luhis , it didn't quite compile as-is because the call to `GetCustomerNameForFooAsync` returns a `Foo` and not a `OneOf<Foo, None>`.

I got it to compile with this:
```csharp
public Task<OneOf<Foo, None>> HandleAsync(int query)
{
	var foo = await GetByIdAsync(query.FooId);

	return await foo.Match<Task<OneOf<Foo, None>>>(
		async f => await GetCustomerNameForFooAsync(f),
		_ => Task.FromResult<OneOf<Foo, None>>(new None()));
}
```
Those explicit conversions are ugly though, I think I'll stick to my earlier version. Would a `MatchAsync` extension method tidy this up?

**Comment by luhis** [comment]
@mattfrear ah yeah, my mistake, Although it did point out another issue with implicit conversions as it prevents you eliding the task.

I haven't done a match async in OneOf, but I have done one with Optional, it's a very similar package, but it's just one type, or nothing.

https://github.com/luhis/shitforum/blob/master/Services/TaskOptionExtensions.cs

**Comment by mcintyre321** [comment]
Hi Matt

I think the cleanest way to write it with the current lib is if you get liberal with `async`:
```
async Task<OneOf<Foo, None>> HandleAsync(GetFooQuery query)
{
	var foo = await GetByIdAsync(query.FooId);

	return await foo.Match<Task<OneOf<Foo, None>>>(
		async f => await GetCustomerNameForFooAsync(f),
		async _ => new None()); //you'll get a warning about it not being async, but ignore it!
}
```

**Comment by mattfrear** [comment]
Thanks gents, closing.

**Comment by mattfrear** [comment]
Haha struggling with this again 3 years later... searched GitHub Issues wondering "has anyone else had this problem" and found this thread again. (I'm using the `Result` class from https://github.com/vkhorikov/CSharpFunctionalExtensions)

This compiles OK
```csharp
private async Task<Result<Pdf>> GetPdfFromBlobStorage(OneOf<BillId, Guid> idOrRoute)
{
    var billIdResult = await idOrRoute.Match(
        id => Task.FromResult(Result.Success(id)),
        async route => await billRoutingRepository.LookupBillId(route));
```

Hating this line: `id => Task.FromResult(Result.Success(id))` but can't get it to compile any other way.

**Comment by mcintyre321** [comment]
async id => Result.Success ?

**Comment by mattfrear** [comment]
Thanks for the reply Harry. 

Yep, that works, it's the same suggestion you made last time. My bad - I missed your comment `//you'll get a warning about it not being async, but ignore it`.

I'm pedantic about not having compiler warnings so I stuck with the ugly Task.FromResult and then edited my message to get rid of the question altogether.

**Comment by leqwasd** [comment]
This also works
```c#
async Task<OneOf<Foo, None>> HandleAsync(GetFooQuery query)
{
	var foo = await GetByIdAsync(query.FooId);

	return await foo.Match(
		async f => await GetCustomerNameForFooAsync(f),
		_ => Task.FromResult<OneOf<Foo, None>>(new None()));
}
```

In this case - you can lose specifying generic for `.Match<T>( ..)`

I think (not sure) - this should be the most optimal solution, since it doesn't produce async context around it which doesn't actually do anything. Maybe comparable with `async _ => new None()` but without the warnings.

**Comment by jacob7395** [comment]
I was going to post a similar suggestion to @leqwasd only change would be the user of a ValueTask but don't think the syntax plays nice with it. I am kind of there with this extension method;

```c#
    public static async ValueTask<TResult> MatchAsync<TResult, T0, T1>(this OneOf<T0, T1> oneOf,
                                                                       Func<T0, ValueTask<TResult>> f0,
                                                                       Func<T1, ValueTask<TResult>> f1)
        => await oneOf.Match(f0, f1);
```

But doesn't quite work, might be able to work nicer as a method in library will look into doing a PR.
