### ISSUE TITLE
ToString() causing a StackOverflowException

### ISSUE THREAD

**Issue by michael-wolfenden** [mcintyre321/OneOf#45]
Given the following

```csharp
public abstract class PaymentResult : OneOfBase<PaymentResult.Success, PaymentResult.Declined, PaymentResult.Failed>
{
	public class Success : PaymentResult { }
	public class Declined : PaymentResult { }
	public class Failed : PaymentResult { public string Reason { get; set; } }
}
```

Calling `ToString()` results in a `StackOverflowException`

```csharp
// Causes a StackOverflowException
new PaymentResult.Declined().ToString();
```

Unfortunately this is completely breaking debugging in any IDE that attempts to evaluate a variable of type `OneOfBase` by displaying it's `ToString()` representation.

**Comment by mcintyre321** [comment]
I suspect this is caused by https://github.com/mcintyre321/OneOf/pull/42. I'll revert it for now and push a new version

**Comment by mcintyre321** [comment]
n
