### ISSUE TITLE
Option to build with reduced maximum option count

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [mcintyre321/OneOf#49]
As it is, the library size is ridiculous, it's over 10 MB, which makes it very prohibitive to use in some case. Most people won't need variants with 30 options. The `System.Action` generic delegate only has variants with up to 16 parameters, for example.

**Comment by ZimM-LostPolygon** [comment]
Ah, just realized OneOf.Extended is exactly for that. Thank you for thinking about this!

**Comment by mcintyre321** [comment]
Are you running an old version? Where did you get the 10mb version from?
