### ISSUE TITLE
ToString() throws NullReferenceException if a value is null (in FormatValue)

### ISSUE THREAD

**Issue by SirUppyPancakes** [mcintyre321/OneOf#50]
This function (which is used in all of the `ToString` implementations):
```
string FormatValue<T>(Type type, T value) => $"{type.FullName}: {value.ToString()}";
```

Throws a `NullReferenceException` whenever one of the contained values is null. 💥

Those pesky nulls always finding their way in!

**Comment by mcintyre321** [comment]
What does a null-valued f# DU do when it's `.ToString`ed...

**Comment by SirUppyPancakes** [comment]
From Visual Studio's F# interactive window:
```
> type SomeDU = One of x: string | Two of y: obj;;
type SomeDU =
  | One of x: string
  | Two of y: obj

> let test = One null;;
val test : SomeDU = One null

> let test2 = Two null;;
val test2 : SomeDU = Two null

> test.ToString();;
val it : string = "One null"

> test2.ToString();;
val it : string = "Two null"

> 
```
I generally completely disallow null in my whole code base, and use an `Option` type instead, but there are times when it comes in handy to `Map` to a null version for quick runtime checking or interop-ing with some API that uses null.

Once C# 8 rolls around, we'll be able to have compile-time checks for this stuff!

**Comment by mcintyre321** [comment]
Any chance of a pull request? I'm not on a PC much at the moment.

**Comment by SirUppyPancakes** [comment]
Sure, yeah I'll try to squeeze it in here soon 👍

**Comment by SirUppyPancakes** [comment]
Finally got around to it, pull request can be found here: https://github.com/mcintyre321/OneOf/pull/51
