### ISSUE TITLE
Consolidate all types into a single namespace

### ISSUE THREAD

**Issue by Jehoel** [mcintyre321/OneOf#52]
I notice that the utility types like `All`, `Error,` `None`, etc are in the `OneOf.Types` namespace.

Is there a reason they're in a child namespace? It seems odd to only have `IOneOf`, `OneOf<T...>` and `OneOfBase<T...>` in `OneOf` but have other types you're bound to use a child namespace.

As a consumer of OneOf, it's a hassle to import two namespaces every time (y'know... scroll back to the top, type out `u.s.i.n.g.<space>O..n.<ctrl+space><down><down><enter>`). I know `<Ctrl> + <Dot>` speeds things up in VS2017 but it isn't perfect when in ambiguous contexts.

Also, I know it sounds crazy - but might you even consider making an alternative NuGet package where the types are pre-inserted into the `System` namespace? (Ordinarily I feel third-party packages should never be in the `System` namespace, but I'd make an exception for this package because it's just so danged _useful_).

**Comment by mcintyre321** [comment]
Heh, really glad you're finding it so useful!

Unfortunately, I suspect that having OneOf inside `System` would put some people off the library, and we're still in the early-adopter phase - once we've gone mainstream I'd happily move it there**.

I came up with the types inside `OneOf.Types` namespace pretty quickly, and I think it needs to be opt in, in case people want to develop their own (possibly better) case types. Maybe I should split it into a `OneOf.Types` library, but I suspect it wouldn't get installed that often...

Maybe it's worth creating your own `OneOf.Contrib.Types` project with types in the root?

**Comment by Jehoel** [comment]
> Maybe I should split it into a OneOf.Types library, but I suspect it wouldn't get installed that often...

Or how about two separate NuGet packages - one with all the types in a single flat namespace, and another without the `Types` types (or in a separate namespace, as we have now)?

**Comment by mcintyre321** [comment]
I think you'd end up with some confusing compatibility issues between the types. I guess we could make

OneOf - meta package
 - OneOf.Types
 - OneOf.Core

and have OneOf.TypesButInOneOfNamespace

but TBH I think this is making life more complicated than it's worth
