### ISSUE TITLE
Deconstruct support

### ISSUE THREAD

**Issue by shoe-diamente** [mcintyre321/OneOf#55]
Would it be possible to add Deconstruct support to this [like this](https://docs.microsoft.com/it-it/dotnet/csharp/deconstruct)?

The use case I have is this:

```
public OneOf<Result1, Error1, Error2> Fn1(...) { ... }
public OneOf<Result2, Error1, Error2, Error3> Fn2(...)
{
    var result = Fn1(...);
    // If result is Error1 just return it
    // If result is Error2 just return it
    // If result is Result1 then:
    //     - If there's some other condition return Error3
    //     - otherwise return the transformation of Result1 to Result2
}
``` 

The way I thought about it is this:

```
public OneOf<Result1, Error1, Error2> Fn1(...) { ... }
public OneOf<Result2, Error1, Error2, Error3> Fn2(...)
{
    var (result, error1, error2) = Fn1(...);
    if (error1 != null) return error 1;
    if (error2 != null) return error 2;
    
    if (Condition(result)) return new Error3();
    return Transform(result);
}
```

**Comment by mcintyre321** [comment]
```
public OneOf<Result2, Error1, Error2, Error3> Fn2(...)
{
    var resultOr12 = Fn1();
    if(result.TryPickT1(out var error1, out resultOr2))
        return error1;
    
    if(result.TryPickT1(out var error2, out result))
        return error2;
    
    if (Condition(result)) return new Error3();
     
    return Transform(result);
}
```

**Comment by shoe-diamente** [comment]
As you can see from the example you posted, this doesn't guarantee that all options are checked. 
In your example:
```
public OneOf<Result2, Error1, Error2, Error3> Fn2(...)
{
    var resultOr12 = Fn1();
    if(result.TryPickT1(out var error1, out resultOr2))
        return error1;
    
    if(result.TryPickT1(out var error2, out result))
        return error2;
    
    if (Condition(result)) return new Error3();
     
    return Transform(result);
}
```

You typed `TryPickT1` twice and that doesn't yield any error.

**Comment by shoe-diamente** [comment]
Even debugging the engine I get:
![Screen Shot 2019-11-15 at 17 02 02](https://user-images.githubusercontent.com/40760781/68957167-c0a3c280-07c9-11ea-905b-ed430e34e965.png)

And as you can see the `ErrorsGuardMetaDataAttribute` gets correctly registered as a default attribute.

**Comment by mcintyre321** [comment]
Ah there was a typo, I've edited it. The second time it should be `if(resultOr2.TryPickT1(out`

**Comment by Drizin** [comment]
If anyone else is also interested in deconstructors: 

https://github.com/Drizin/OneOf.DeconstructorExtensions

This library extends `OneOf<>` and `OneOfBase<>` with methods to deconstruct them into the underlying types. The major non-trivial addition here is that non-nullable value types will be automatically converted into nullable types, which means that deconstructing the Tuple will always return a single non-null value (all other values will be null), respecting the same semantic of union-types.
There are also extensions to convert to `Tuple<>` or `ValueTuple<>`
