### ISSUE TITLE
.NET Framework 3.5

### ISSUE THREAD

**Issue by davidhunter22** [mcintyre321/OneOf#57]
Hi, Can the library support .NET Framework 3.5. I tried a local build adding net35 to <TargetFrameworks> and it all seemed to build. Sadly 3.5 is still supported by Microsoft and for various reasons we have to build against it as a minimum version.

**Comment by mcintyre321** [comment]
You can create PR with 3.5 and we can see what happens. If it messes up the
nuget package I'll revert.
