### ISSUE TITLE
Generic As<T>

### ISSUE THREAD

**Issue by davidhunter22** [mcintyre321/OneOf#58]
Have you considered a generic As<T>, something like the following

```
        public T As<T>( )
        {
            if( typeof( T ) == typeof( T0 ) ) return (T)(object)AsT0;
            if( typeof( T ) == typeof( T1 ) ) return (T)(object)AsT1;
            if( typeof( T ) == typeof( T2 ) ) return (T)(object)AsT2;

            throw new InvalidOperationException( $"Cannot return as {typeof( T ).Name} does not contain that type" );
        } 
```

So you could write things like

```
    OneOf<int,double,string> x = ...

    var y = x.As<string>( );
```
This would avoid having to remember index values and having to change them if you say add an extra type. Note this is similar to the C++ std::variant get<T> function which is very useful.

I did try implementing the above and it did seem to work. I could make a pull request but wanted to check if it would be accepted first.

**Comment by Jehoel** [comment]
There are problems with your approach:

* This doesn't have the advantage of compile-time type-safety verification though.
* This fails if the same type is used for different arguments, e.g. if `T0` and `T1` are both `String` but the value is in the field for `T1` then it will incorrectly return `AsT0`.
* For performance reasons you'll want to avoid the `(object)` cast because that will cause boxing of value-types.

**Comment by zspitz** [comment]
In addition, you probably want:
```
if (typeof(T0).IsAssignableFrom(typeof(T)) ...
```
Otherwise, if `T` inherits from or implements `T0`, the `if` test will fail.

**Comment by zspitz** [comment]
You could try something like this:
```csharp
public bool TryFirstOfT<T>(ref T result) {
    switch (_index) {
        case 0 when AsT0 is T result0:
            result = result0;
            return true;
        case 1 when AsT1 is T result1:
            result = result1;
            return true;
        case 2 when AsT2 is T result2:
            result = result2;
            return true;
    }
    return false;
}
```
The name/signature makes it clear that the method is looking for the value only if it matches the specified type; and the method avoids boxing and unboxing.

**Comment by mcintyre321** [comment]
Closing as the "doesn't have the advantage of compile-time type-safety verification" is critical
