### ISSUE TITLE
Question: Converting from subtype value to class derived from OneOfBase

### ISSUE THREAD

**Issue by zspitz** [mcintyre321/OneOf#66]
Given the following definition:

```csharp
public class MetaValue : OneOfBase<
    bool,
    string
> { }
```
How do I get from either a `bool` or `string` to `MetaValue`?

For `OneOf`, this is pretty straightforward:
```csharp
OneOf<bool, string> x = true;
x = "abcd";
```
But trying something similar with `OneOfBase`:
```csharp
MetaValue m = true;
```
doesn't compile with:

> CS0266: Cannot implicitly convert type 'bool' to 'PandocFilters.Types.MetaValue'. An explicit conversion exists (are you missing a cast?)

And the explicit cast:

```csharp
var m = (MetaValue)true;
```

fails at runtime with **System.InvalidCastException**.

How am I supposed to create an instance of MetaValue?

**Comment by zspitz** [comment]
The code presented [here](https://github.com/mcintyre321/OneOf/issues/4#issuecomment-252295834):

```csharp
namespace MyNamespace {
    public class Await {
        public static Await Default { get; } = new Await();
    }

    public class Sygnal<T> : OneOfBase<T, Exception, None, Await> {
        public static Sygnal<T> Await { get; } = (Sygnal<T>) MyNamespace.Await.Default; 
    }
}
```
fails at runtime with the same **InvalidCastException** on the property getter; it still fails even without the generic parameter.

The cast exception makes sense, because `Sygnal<T>` in the above example might theoretically have additional members defined on it, and thus be a different type from `OneOfBase<T, Exception, None, Await>`. (Even though admittedly, a `Sygnal<T>` is assignable to the `OneOfBase`.)

**Comment by zspitz** [comment]
I can resolve this by:

1. Creating an extension method to return the index of a `OneOf`:

        internal static int Index<T0, T1>(this OneOf<T0, T1> oneof) =>
            oneof.Match(
                x => 0,
                x => 1
            );

2. Creating a constructor on my derived class which takes the corresponding `OneOf`, and which passes the index (using the above extension method) and appropriate value to the `OneOfBase` constructor:

        public MetaValue(OneOf<
            bool,
            string,
        > value) : base(
            value.Index(),
            value.IsT0 ? value.AsT0 : default!,
            value.IsT1 ? value.AsT1 : default!
        ) { }

I propose the following:

1. Expose the index on `OneOf`, at least `internal`ly, so it can be accessed from `OneOfBase`.
2. Have a `OneOfBase` constructor which takes a `OneOf` instance, and which produces values to the "full" constructor.

**Comment by mcintyre321** [comment]
https://github.com/mcintyre321/OneOf/issues/4#issuecomment-735648312

**Comment by zspitz** [comment]
@mcintyre321 It's a requirement that all the subtypes of `OneOfBase` inherit from the derived type? So a class which inherits from `OneOfBase<string, bool>` is useless?

**Comment by zspitz** [comment]
@mcintyre321 Do you have philosophical or technical objections to [the above changes](https://github.com/mcintyre321/OneOf/issues/66#issuecomment-735595138) to `OneOfBase`?

1. Exposing the OneOf index value to OneOfBase, and
2. Having a protected constructor on OneOfBase that would take the corresponding OneOf

If you think it would add value I would be willing to submit a PR.

**Comment by mcintyre321** [comment]
1. Yes, I would like the index exposed, ideally as a property on IOneOf. Jut haven't got round to it yet.
2. I have avoided this in favour of the (index, ..., TValue, ...) ctors so far, to reduce ambiguity when you have two or more types in the parameters that are polymorphic. It might not be a problem, but I haven't thought through all the complexities. 

I did consider changing `OneOfBase<T0, T1>` to `OneOfBase<T0, T1, TThis>`, which would (I think) enable a `SomeOneOfBase.FromT1(T1 t1)` method to be added (in a similar way to in my ValueOf project)

There are also possibly some things that could be done with .NET 5 Source Generators for hierarchies, but again, I haven't looked into it yet.

**Comment by mcintyre321** [comment]
Sorry have just read your comment properly about the ctor. Thinking!

**Comment by mcintyre321** [comment]
I've just done a little test in LINPad ([here](http://share.linqpad.net/8uwmr9.linq), adding 

```
protected OneOfBase(OneOf<T0, T1> input)
	{
		_index = ((IOneOf)input).Index;
		if (input.IsT0) _value0 = input.AsT0;
		if (input.IsT1) _value1 = input.AsT1;
	}
```
let you write 

```
public class Polarity : OneOfBase<Positive, Negative>
{
	Polarity(OneOf<Positive, Negative> value) : base(value)	{ }
	public static implicit operator Polarity(Positive _) => new Polarity(_);
	public static implicit operator Polarity(Negative _) => new Polarity(_);
}
```
which is very nice

**Comment by mcintyre321** [comment]
I'm just a bit worried that this might make certain hierarchies ambiguous. OTOH if we remove the other OneOfBase ctors it's a non-compiling change (which is a good thing compared to a silently breaking change), and people can raise issues if there is a situation like that.

**Comment by mcintyre321** [comment]
I like it!

I think I would accept an MR with these changes. You know you have to run a linqpad script to generate the code, right?

So
1. add an int Index property on IOneOf
2. implement it in OneOf and OneOf base
3. add a OneOf ctor to OneOf base types 

```
protected OneOfBase(OneOf<T0, T1> input)
	{
		_index = ((IOneOf)input).Index;
                switch(_index) 
                { 
                    case 0: _value0 = input.AsT0; break;
                    ...
                    case  N: _valueN = input.AsTN; break;
                    default: throw new InvalidOperationException();
	}
```

4. while you are in there, remove the other ctors from OneOfBase, (and the implicit casts that are on OneOf base)
5. Update the tests and docs

If you get that in a PR, I'll do a major version bump. Sorry, haven't got time to implement this myself.

**Comment by zspitz** [comment]
> while you are in there, remove the other ctors from OneOfBase

Why is this necessary? Is it actually harmful? What if someone wants to explicitly pass in the values, instead of creating an additional OneOf?

**Comment by zspitz** [comment]
@mcintyre321 

> while you are in there, remove the other ctors from OneOfBase

Each class in OneOfBase.cs currently has two constructors: the index-based constructor, and the parameterless constructor. 

```csharp
```
protected OneOfBase(int index, T0 value0 = default(T0))
{
    _index = index;
    _value0 = value0;
}

protected OneOfBase()
{
    if (this is T0)
    {
        _index = 0;
        _value0 = (T0)(object)this;
        return;
    }
}
``````
The functionality of both constructors could be replaced with a single OneOf-accepting constructor. Is that what you mean?

**Comment by mcintyre321** [comment]
Yes - don't think you need it any more. This will also force a breaking
change in any consumers of the library when they upgrade (which is
desirable IMO).

**Comment by zspitz** [comment]
@mcintyre321 I think the parameterless constructor is still needed for OneOfBase of multiple derived classes:

```csharp
public class TrueFalseOrNull : OneOf.OneOfBase<TrueFalseOrNull.True, TrueFalseOrNull.False, TrueFalseOrNull.Null>
{
    public class True : TrueFalseOrNull { }
    public class False : TrueFalseOrNull { }
    public class Null : TrueFalseOrNull { }

// ...
```

because `this` can't be passed into the base constructor.

**Comment by zspitz** [comment]
@mcintyre321 I've created a PR #67.

**Comment by mcintyre321** [comment]
Zev, would you mind doing another MR, removing the parameterless
constructor (and updating the docs)?

My reasoning is

 - OneOfBase is intended for named hierarchies, and inheritance with
default ctor was just sugar so you can skip the implicit cast operator
 - inheriting is however, nasty as it
   - can throw an exception
   - can lead to nasty recursion errors
https://github.com/mcintyre321/OneOf/issues/28
   - makes it non-obvious how to implement a OneOfBase (having a single
ctor with parameters means there is only one way to initialize).

If you don't have time let me know. My dev machine isn't set up for OneOf
at the moment, but I will be get round to it at some point
and thanks!

**Comment by zspitz** [comment]
@mcintyre321 Thanks for taking the PR.

I don't think it possible to remove the parameterless constructor; otherwise it will be impossible to define named hierarchies. Without the parameterless constructor, the only constructor we have for OneOfBase is the one that takes `OneOf` as a parameter. There's a fundamental problem with hierarchal types: we can't pass in `this` -- the current object -- to a chained base constructor.

Therefore, the following code will not compile:
```csharp
namespace Test {
    public abstract class YesOrNo : OneOfBase<YesOrNo.Yes, YesOrNo.No> {
        public class Yes : YesOrNo { }
        public class No : YesOrNo { }
    }
}
```
with the following error:

> CS7036: There is no argument given that corresponds to the required formal parameter 'input' of 'OneOfBase<YesOrNo.Yes, YesOrNo.No>.OneOfBase(OneOf<YesOrNo.Yes, YesOrNo.No>)'

Or in other words, we're not passing anything to single parameterized base constructor.

We could define a OneOf-accepting constructor on `YesOrNo`, and pass its value to the `OneOfBase` constructor:

```csharp
namespace Test {
    public abstract class YesOrNo : OneOfBase<YesOrNo.Yes, YesOrNo.No> {
        private YesOrNo(OneOf<Yes,No> input) : base(input) {}
        public class Yes : YesOrNo { }
        public class No : YesOrNo { }
    }
}
```

but that only pushes the problem back up to the `Yes` and `No` derived classes. We might try to resolve this by writing `Yes` and `No` constructors which would pass a new instance of their own type into the base constructor:

```csharp
namespace OneOf.Types {
    public abstract class YesOrNo : OneOfBase<YesOrNo.Yes, YesOrNo.No> {
        private YesOrNo(OneOf<Yes,No> input) : base(input) {}

        public class Yes : YesOrNo {
            public Yes() : base(new Yes()) { }
        }
        public class No : YesOrNo {
            public No() : base(new No()) { }
        }
    }
}
```
but aside from being far more complex than directing users not to call the parameterized base constructor, I think it would also recurse infinitely. (`new Yes()` calls `new Yes()` ...)

Having a default parameterless constructor means we don't need to pass in the current instance, because we can already access it via the `this` keyword; we can use the type of `this` to determine the index, without relying on any external input.

---

Note that this only an issue for named hierarchies; if the types aren't part of a hierarchy then it's trivial to forward external values / instances into the base constructor:

```csharp
public class StringOrInt : OneOfBase<string, int> {
    public StringOrInt(string s) : base(s) { }
    public StringOrInt(int i) : base(i) { }
    // alternatively, use a single constructor, taking OneOf<string, int>, or even taking OneOf<int, string>
}
```

**Comment by mcintyre321** [comment]
Yep - I'm saying we shouldn't allow inheritance based hierarchies, going forward. e.g. for YesOrNo, people should use :

```
  public class YesOrNo : OneOfBase<YesOrNo.Yes, YesOrNo.No> {
        public YesOrNo(OneOf<YesOrNo.Yes, YesOrNo.No> _): base(_){ }
        public class Yes { }
        public class No { }
        public static implicit operator YesOrNo(Yes _) => new YesOrNo(_);
        public static implicit operator YesOrNo(No _) => new YesOrNo(_);
  }
```
I think the inheritance based approach can result in some really weird situations if people put behaviour into the base (YesOrNo) class. Better to prevent that from happening.

**Comment by zspitz** [comment]
@mcintyre321 I've added a new PR #68 with the additional changes.

**Comment by julealgon** [comment]
This was such a fundamental change to how `OneOfBase` is used... I honestly wish there was some deprecation notice "intermediate step" before this huge breaking change was introduced.

This will also significantly complicate tests on my end, which were relying on `BeOfType<T>` (fluent assertions) for verification. Those won't work anymore :(

The boilerplate code needed for the extra conversions is also highly undesirable.

Oh well...

**Comment by julealgon** [comment]
This also now raises FXCop warnings on the conversions, which will result in even more boiler plate code:

![image](https://user-images.githubusercontent.com/461579/101541671-84b53f80-3980-11eb-8dd1-c00b41e9994c.png)

**Comment by mcintyre321** [comment]
At least I bumped the major version number..

Seriously though, sorry to have had to break your code. The inheritance
approach caused some nasty bugs, and so I wanted rid. Unfortunately a OneOf
type heirarchy really balloons the assembly size, so I didn't want to keep
around a deprecated type.

Maybe we can reintroduce the ctor with a Deprecated attribute, or make
another assembly/package with a OneOfBaseLegacy type that would be the same
as the old one, if it's going to be a big problem.

**Comment by julealgon** [comment]
@mcintyre321 
> At least I bumped the major version number..

I'm not questioning that. That was a good move. My point is on how abrupt this was. Usually, APIs that are changed drastically or deprecated have a notice between versions to allow devs to accomodate, along with some migration strategy to guide people going from the old to the new version.

> The inheritance approach caused some nasty bugs, and so I wanted rid.

I know. I actually updated the library as a test to see if a problem I was having would go away. I was relying on reflection (not me, but a library I'm using, 'Serilog') to "serialize" generic instances of type T and I just added an integration today that started processing my command objects, which all relied on `OneOf`: I was getting infinite loops with exceptions in the console right after adding that integration.

I've now updated the library (just in one component) and it indeed fixed the issue.

I apologize if I was too harsh on my previous comment, but I just got caught by surprise about the size of the breaking changes here... usually breaking changes are small stuff that affect just a few places and are easy to apply, not so much this one... That coupled with [the lack of proper release notes](https://github.com/mcintyre321/OneOf/issues/70) and lack of information on how to migrate made it a bit harder for me. I still have to update a handful of projects with the new approach, and all of my tests will for sure break due to this and require less-than-clean verification now that `BeOfType` won't work anymore.

> Maybe we can reintroduce the ctor with a Deprecated attribute, or make
another assembly/package with a OneOfBaseLegacy type that would be the same
as the old one, if it's going to be a big problem.

I wouldn't go as far as to say I need a separate assembly with the older logic or reintroducing the ctor with the deprecation notice, as it shouldn't take _that_ much to adapt all my code. But perhaps in the future, my wish for the library is for it to be a bit less aggressive on these API changes, perhaps doing a phased approach by adding an intermediary version with the [Deprecated] attributes to give people more time to migrate when they can, instead of taking the hit immediately like I did.

One could say "well you could just not update", but that wasn't an option seeing as I was getting the infinite recursion problem and it would probably be much harder or even impossible for me to fix it otherwise.

I do appreciate that the problem was fixed, don't get me wrong.

**Comment by zspitz** [comment]
@mcintyre321 As the author of the PR in question, is it too late to incorporate some kind of release notes / migration guide? Where should it go?

**Comment by mrtristan** [comment]
@mcintyre321 - a good change overall, but definitely a bit painful. too much research required to identify what's been changed and how to roll with it.

dealing with this change means browsing commits / issues / pr's to land on this thread which requires a full read.

if you don't have time to deal with release notes and such, i'd suggest forcing contributors to do so as people submit PR's so you at least get that for free.

in any event, still a cool as hell repo.

**Comment by zspitz** [comment]
@mrtristan

> forcing contributors to do so as people submit PR's

I don't think it necessary to "force"; all that's needed is a place (perhaps opening the wiki?) where it would be appropriate to store such information.

[This section](https://github.com/mcintyre321/OneOf#reusable-oneof-types-using-oneofbase) in the README covers valid usage of `OneOfBase`. How could it be improved? What use cases aren't covered?

**Comment by mcintyre321** [comment]
Zev, I'd rather keep the documentation in the readme as much as
possible. Tristan, a PR for the readme with an upgrade notes in the
OneOfBase section would be welcomed.
