### ISSUE TITLE
Add description to README of how to use OneOf and OneOfBase types with `switch` statements and expressions

### ISSUE THREAD

**Issue by zspitz** [mcintyre321/OneOf#69]
Now that `Index` is exposed on all `OneOf` and `OneOfBase`, via the `IOneOf.Index` property, it should be trivial to use C# control flow syntax as an alternative to `Match`, `Switch`, and `TryPick𝑥`:

```csharp
public class StringOrNumber : OneOfBase<string, int> {
    StringOrNumber(OneOf<string, int> _) : base(_) { }
    public static implicit operator StringOrNumber(string _) => new StringOrNumber(_);
    public static implicit operator StringOrNumber(int _) => new StringOrNumber(_);
}

StringOrNumber x = 5;
int? result = x.Index switch {
    0 => int.TryParse(x.AsT0, out var n) ? n : null,
    1 => x.AsT1
};
```

Should this be documented in the README?

It might be preferable to do this in certain case where creating all the necessary delegate objects could be a performance or memory issue.

**Comment by mcintyre321** [comment]
So I don't think this is a good idea - c# match syntax is not exhaustive,
so if you use a switch expression, and then add an extra type to the OneOf,
you won't get a compiler error (which in my opinion is the whole point of a
OneOf, otherwise probably just use object and switch on type).

**Comment by zspitz** [comment]
> otherwise probably just use object and switch on type

When using OneOf, there's no boxing and unboxing of value types. I don't have hard data for the actual performance/memory consumption implications, but I understand that in some situations there might be a heavy penalty

**Comment by mcintyre321** [comment]
Hopefully those delegate performance issues you mention in OP can be dealt with by using c#9's static lambdas. I imagine it's super JIT friendly if you do 

```
int? result = x.Match(
		static x => int.TryParse(x, out var n) ? n : null as int?,
		static x => x
	);
```

**Comment by zspitz** [comment]
Agreed. Closing.
