### ISSUE TITLE
Missing release notes?

### ISSUE THREAD

**Issue by julealgon** [mcintyre321/OneOf#70]
I noticed the project got a major version bump recently, however I could not find any information about this new release, what new features there are, bug fixes, etc. I noticed the "Releases" section here on github is empty, so you haven't been using it.

Are there any plans to expose release notes to consumers in a cleaner, easy-to-find way?

**Comment by mcintyre321** [comment]
I use continuous deployment from master to minimise how much time I need to
spend managing the project, and am unlikely to start using the releases
feature any time soon as it would make my workflow more complex.

I'll ask  people raising PRs to add more info in the readme from now on
though.

**Comment by julealgon** [comment]
Thanks for getting back on this.

It may sound entitled for me to say this, but I honestly believe you should spend some time on making your CI/CD process more robust for this library. It currently sits at around 1 million downloads which is substantial already.

I understand your concerns, but can't you just automate all of it from your CI server? I don't think you'd need to make any changes to branching strategy or anything of the like (after all, trunk-based is preferred these days anyways so I'd never propose changing that).

If that's really not possible, one idea would be to add some notes to the readme about the versions (like a small section). At least that would allow one to find it with a quick search for "release notes" or "patch notes" or whatever.

**Comment by mcintyre321** [comment]
Sadly the number of downloads doesn't give me more time to work on the
project.!

Happy to accept a PR with your readme section though, and if there are
breaking changes I'll ask the PR author to add something before i accept
the PR.

Hopefully there won't be many more, if they do a decent job of unions in
the next c# version
