### ISSUE TITLE
Lambda syntax to OneOf of delegate types

### ISSUE THREAD

**Issue by zspitz** [mcintyre321/OneOf#71]
The following:
```csharp
OneOf<
    Func<int, int>,
    Func<string, string>
> del = (int i) => i;
```
does not compile, with:

> Cannot convert lambda expression to type '`OneOf<Func<int, int>,Func<string, string>`' because it is not a delegate type.

I can work around this with the following:

```csharp
OneOf<
    Func<int, int>,
    Func<string, string>
> del = (Func<int, int>)((int i) => i);
```

or

```csharp
var del = OneOf<
    Func<int, int>,
    Func<string, string>
>.FromT0(i => i);
```

But is there some way for OneOf to figure out that all the subtypes are delegate types, and pass this information to the compiler for an implicit conversion?

**Comment by mcintyre321** [comment]
I'm not surprised, c# type inference for lambdas is pretty poor, you
generally need an explicit cast when setting a lambda variable.

Does it work implicitly if you only have a single lambda in the OneOf
params?

**Comment by zspitz** [comment]
@mcintyre321 

> Does it work implicitly if you only have a single lambda in the OneOf params?

No.

---

Another workaround is to define a helper function:

```csharp
static Func<T, T> Fn<T>(Func<T, T> fn) => fn;
```

which I can then use like this:

```csharp
OneOf<
    Func<int, int>,
    Func<string, string>
> del = Fn((int i) => i);
```

for my ultimate goal of passing multiple differently-typed lambdas to another method, whose parameter would be the above `OneOf` type.

```csharp
MyMethod(
    Fn((int i) => i),
    Fn((string s) => s)
);
```

**Comment by mcintyre321** [comment]
Surely `static Func<T, T> λ<T>(Func<T, T> fn) => fn;` is what you want :D

**Comment by zspitz** [comment]
> Surely `static Func<T, T> λ<T>(Func<T, T> fn) => fn;` is what you want :D

@mcintyre321 I'm afraid it's Greek to me :) . Why would calling the static function `λ` instead of `Fn` make a difference?

**Comment by mcintyre321** [comment]
Aesthetics! What you really want is an invisible Unicode character for
`Fn`, then the code will look perfect!
