### ISSUE TITLE
Auto-generation code improvements

### ISSUE THREAD

**Issue by zspitz** [mcintyre321/OneOf#73]
1. Move the code from a `.linq` file to an additional project under the solution. Will allow using IDE features and debugging without having to purchase a LINQPad license.
2. Set `LangVersion` in the `OneOf.csproj` and `OneOf.Extended.csproj` to `9.0`, and emit newer C# language syntax such as switch expressions. Note that for much of the syntax, a higher .NET TFM is not required.
3. Remove `for` and multiple `AppendLine` calls in an iteration; prefer a single `AppendLine` with joined strings.

**Comment by zspitz** [comment]
@mcintyre321 Can I get your input on this, so I can move forward on #72 ?

**Comment by mcintyre321** [comment]
Hi, sorry, missed this one at the time.

Happy for all of these to go ahead, thanks for your interest in the project!

**Comment by mcintyre321** [comment]
🎉🎉🎉!
