### ISSUE TITLE
Using OneOf without adding dependency on Newtonsoft.Json

### ISSUE THREAD

**Issue by jnm2** [mcintyre321/OneOf#8]
Some people might appreciate having a OneOf package without pulling in Newtonsoft.Json if they aren't using it.

Is it possible to allow `IOneOf` to interop with Newtonsoft.Json through BCL mechanisms rather than through a JsonConverter? For example, implicit operator or TypeConverter?

**Comment by mcintyre321** [comment]
I think I'm going to move the serialization stuff into a second
project/nuget package (OneOf.Serialization.Newtonsoft or simikar) when I
get a chance, serialization is too opinionated for the core project

**Comment by mcintyre321** [comment]
I've removed it, for now people can copy the serializer class from the OneOf.Tests project

**Comment by zspitz** [comment]
Shoutout to @dpraimeyuu for the OneOfConverter at https://github.com/dpraimeyuu/OneOf.Serialization/blob/master/OneOf.Serialization/OneOfJsonConverter.cs.

I've also written a similar converter at https://github.com/zspitz/PandocFilters/blob/main/PandocFilters/Converters.cs#L9.
