### ISSUE TITLE
ASP.NET Controller InvalidOperationException

### ISSUE THREAD

**Issue by chrispdraycott** [mcintyre321/OneOf#81]
Couldnt find anyones contact details to email so putting this on here.
Can someone explain why I get the following error in my ASP.NET 5 MVC WebAPI project:

InvalidOperationException: Cannot return as T1 as result is T0

I have an API Controller Get Method defined as:
public OneOf<String,Int32> GetTest()
        {
            if (_Message != null)
                return "NotNull";
            else
                return 0;
        }
Why do i get the exception? I know its to do with Json Serialization but not sure how to handle this? 
Any help appreciated.

**Comment by romfir** [comment]
The ```System.Text.Json``` serialzier tries to serialize all public properties (including AsT0, AsT1 etc) e.g. when ```OneOf<String,Int32>``` is of type Int32 (T1) and serialzier tries to read String (T0), OneOf throws ```InvalidOperationException```
https://github.com/mcintyre321/OneOf/blob/3b733c7a13d38fb13202e9e3061d4e8f0e135c9b/OneOf/OneOfBaseT1.generated.cs#L36-L39
I had the same problem and hadled it with a custom JsonConverterFactory, basically I'm serializing all types derived from IOneOf in the same way - using ```IOneOf.Value```
```csharp
public class OneOfConverterFactory : JsonConverterFactory
  {
      public override bool CanConvert(Type typeToConvert)
      {
          if (!typeToConvert.IsGenericType)
              return false;

          return typeof(IOneOf).IsAssignableFrom(typeToConvert);
      }

      public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
          => new OneOfConverter();
  }
```
```csharp
public class OneOfConverter : JsonConverter<IOneOf>
    {
        public override IOneOf? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            => throw new NotSupportedException();

        public override void Write(Utf8JsonWriter writer, IOneOf value, JsonSerializerOptions options)
            => JsonSerializer.Serialize(writer, value.Value, value.Value.GetType(), options);
    }
```
and in the Startup.cs
```csharp
public void ConfigureServices(IServiceCollection services)
{
...
services.AddMvc()
                .AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.Converters.Add(new OneOfConverter());
                    options.JsonSerializerOptions.Converters.Add(new OneOfConverterFactory());
                });
...
}
```

**Comment by Paul-Williams** [comment]
This appears to be answered. Should the issue not be closed?
