### ISSUE TITLE
Match Syntax Exception

### ISSUE THREAD

**Issue by xts-velkumars** [mcintyre321/OneOf#82]
Hi All, 

I'm just exploring OneOf for my Integration Test. 

I'm getting syntax error, while doing below. Can you please help me to resolve this? 

![image](https://user-images.githubusercontent.com/13570225/114307178-1df58d80-9afc-11eb-9bb8-2f0092f5fdc1.png)

```
OneOf<User, InvalidName, NameTaken> response = await CreateUser("username");

 response.Match(
                user =>
                {
                    Console.Write("I'm User");
                },
                name =>
                {
                    Console.Write("I'm name ");
                },
                taken =>
                {
                    Console.Write("I'm taken ");
                });
```

```
public async Task<OneOf<User, InvalidName, NameTaken>> CreateUser(string username)
        {
            if (username is null)
                return new InvalidName();
            if (username == "Test User")
                return new NameTaken();
            var user = new User();
            return user;
        }
```

**Comment by rtkelly13** [comment]
You are getting this because the `Match` method expects a value to be returned from each method passed in. Try using the `Switch` method instead.

**Comment by xts-velkumars** [comment]
@rtkelly13 

Thank you, its working as excepted

**Comment by mcintyre321** [comment]
Thanks for raising this issue.

Now that C# itself supports first class switch expressions, the design of
OneOf, where .Switch is for statements, and .Match is for expressions is no
longer as idiomatic as it once seemed...

I could perhaps get rid of .Switch, by renaming .Switch to match (i.e.
overloading .Match with an Action/statement based method). It's probably
not worth it though, as it would be a breaking chance, particularly with
Unions on the language roadmap...
