### ISSUE TITLE
How to accomodate null values as a one of return

### ISSUE THREAD

**Issue by raysaik** [mcintyre321/OneOf#91]
I am refactoring some code and have a method which has to return null in certain conditions

public OneOf<ValidType, FirstInavlidType, SecndInvalidType> GetXXZZZZZXX(string s, string a)
{
 ....
 if(conditions) return null;

}

How do i accomodate this.

**Comment by mcintyre321** [comment]
You can't (and shouldn't) return null, as it's a struct, but you can return
OneOf<ValidType, FirstInavlidType, SecndInvalidType, OneOf.Types.None>
